image: ubuntu:trusty

build:
  stage: build
  before_script:
    - apt update && apt -y install build-essential texinfo grub-pc-bin xorriso wget m4 autoconf
  script:
    - cd build-tools && bash build.sh distclean && bash build.sh
    - make aquila.iso -j$(nproc)
  # cache:
  #   paths:
  #   - build-tools/pkgs
  #   - build-tools/binutils-2.28
  #   - build-tools/gcc-7.3.0
  #   - build-tools/autoconf-2.69
  #   - build-tools/automake-1.12.1
  #   - build-tools/sys
  artifacts:
    paths:
      - aquila.iso
